kind: Service
apiVersion: v1
metadata:
  name: nfs-service
spec:
  selector:
    role: nfs-server
  ports:
    - name: nfs
      port: 2049
    - name: rpcbind
      port: 111
    - name: mountd
      port: 20048
