kind: Service
apiVersion: v1
metadata:
  name: nfs-service
spec:
  selector:
    role: nfs-server
  type: NodePort
  ports:
    - name: nfs
      port: 2049
      nodePort: 32049
    - name: rpcbind
      port: 111
      nodePort: 30111
    - name: mountd
      port: 20048
      nodePort: 32048