kind: Pod
apiVersion: v1
metadata:
  name: nfs-server
  labels:
    role: nfs-server
spec:
  containers:
    - name: nfs-server-container
    image: itsthenetwork/nfs-server-alpine:6-arm
    env: 
    - name: SHARED_DIRECTORY
      value: '/exports'
    ports:
    - name: nfs
      containerPort: 2049
    - name: mountd
      containerPort: 20048
    - name: rpcbind
      containerPort: 111
    securityContext:
      privileged: true
    volumeMounts:
    - name: nfs-pv
      mountPath: /exports
  volumes:
  - name: nfs-pv
    persistentVolumeClaim:
      claimName: nfs-pvc
  nodeSelector:
    disktype: external