kind: Service
apiVersion: v1
metadata:
  name: nfs-service
spec:
  selector:
    role: nfs
  type: NodePort
  ports:
    - name: tcp-2049
      port: 2049
      nodePort: 32049
    - name: udp-111
      port: 111
      nodePort: 30111
