apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.43.0.20
    path: /homeassistant-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: utilities
  name: homeassistant-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
