apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
