apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-pv
  labels:
    type: local
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/external/config"
