apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  labels:
    name: redis-pod
spec:
  type: ClusterIP
  selector:
    name: redis-pod
  ports:
  - port: 53
    protocol: TCP
  - port: 53
    protocol: UDP
  - port: 80