apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  labels:
    name: pihole-deployment
spec:
  type: ClusterIP
  selector:
    name: pihole-deployment
  ports:
  - port: 53
    protocol: TCP
  - port: 53
    protocol: UDP
  - port: 80