apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  labels:
    name: pihole-deployment
spec:
  type: ClusterIP
  clusterIP: 10.43.0.21
  selector:
    name: pihole-deployment
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    protocol: UDP
  - port: 80
    name: http