apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  labels:
    name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pihole
  template:
    metadata:
      labels:
        name: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: http
          containerPort: 80
        env:
        - name: TZ
          value: Europe/London
        - name: DNS1
          value: 9.9.9.9
        - name: DNS2
          value: 149.112.112.112
        - name: ServerIP
          value: 192.168.1.101
        volumeMounts:
        - name: pihole-pv
          mountPath: /etc/pihole
        - name: pihole-pv-dns
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: pihole-pv
        persistentVolumeClaim:
          claimName: pihole-pvc
      - name: pihole-pv-dns
        persistentVolumeClaim:
          claimName: pihole-pvc-dns
      nodeSelector:
        nodetype: master
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  type: ClusterIP
  clusterIP: 10.43.0.21
  selector:
    name: pihole
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    protocol: UDP
  - port: 80
    name: http