apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv-dns
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/pihole/etc-dnsmasq.d"
