apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  type: ClusterIP
  selector:
    name: pihole
  ports:
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  - port: 80
    targetPort: 80
    name: http