apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv-dns
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.43.0.20
    path: "/pihole/etc-dnsmasq.d"
