kind: Pod
apiVersion: v1
metadata:
  name: nfs-server
  namespace: storage
  labels:
    role: nfs-server
spec:
  containers:
  - name: nfs-server-container
    image: itsthenetwork/nfs-server-alpine:6-arm
    env: 
    - name: SHARED_DIRECTORY
      value: '/shared'
    ports:
    - name: nfs
      containerPort: 2049
    - name: mountd
      containerPort: 20048
    - name: rpcbind
      containerPort: 111
    securityContext:
      privileged: true
    volumeMounts:
    - name: nfs-pv
      mountPath: /shared
  volumes:
  - name: nfs-pv
    persistentVolumeClaim:
      claimName: nfs-pvc
  nodeSelector:
    disktype: external
---
kind: Service
apiVersion: v1
metadata:
  namespace: storage
  name: nfs-service
spec:
  type: ClusterIP
  clusterIP: 10.43.0.20
  selector:
    role: nfs-server
  ports:
    - name: nfs
      port: 2049
    - name: rpcbind
      port: 111
    - name: mountd
      port: 20048
