apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-nfs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.0.20
    path: "/redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: storage
  name: redis-nfs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
