apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine:6-arm
        env: 
        - name: SHARED_DIRECTORY
          value: '/shared'
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /shared
            name: nfs-pv
      volumes:
        - name: nfs-pv
          persistentVolumeClaim:
            claimName: nfs-pvc
      nodeSelector:
        disktype: external