apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.43.0.20
    path: "/pihole/etc-pihole"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
