apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv-dns
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.43.0.20
    path: "/pihole/etc-dnsmasq.d"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: utilities
  name: pihole-pvc-dns
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
