apiVersion: v1
kind: Service
metadata:
  namespace: utilities
  name: pihole-nodeport
spec:
  type: NodePort
  selector:
    name: pihole
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    protocol: UDP
  - port: 80
    name: http
    nodePort: 30080