apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: pihole.cherry.pi
    http:
      paths:
      - path: /
        backend:
          service: 
            name: pihole
            port:
              number: 80
