apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: approot.bar.com
    http:
      paths:
      - backend:
          serviceName: pihole
          servicePort: 80
        path: /pihole(/|$)(.*)