apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: storage
  labels:
    name: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: storage
  name: postgres
spec:
  type: ClusterIP
  clusterIP: 10.43.0.19
  selector:
    name: postgres
  ports:
  - name: postgres-port
    port: 5432
    protocol: TCP