apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  clusterIP: 10.43.0.22
  selector:
    name: redis-pod
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
