apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  labels:
    name: redis-pod
spec:
  type: ClusterIP
  clusterIP: 10.43.0.22
  selector:
    name: redis-pod
  ports:
    - port: 6379
      protocol: TCP
