apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redispv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  nfs:
    server: dbc56.efs.us-west-2.amazonaws.com
    path: "/redis"