apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  labels:
    name: redis-pod
spec:
  type: ClusterIP
  clusterIP: 10.42.0.70
  selector:
    name: redis-pod
  ports:
    - port: 6379
      nodePort: 30379
      protocol: TCP
