apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  labels:
    name: redis-pod
spec:
  type: NodePort
  selector:
    name: redis-pod
  ports:
    - port: 6379
      nodePort: 30379
      protocol: TCP
