apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
spec:
  containers:
  - image: redis
    name: redisdb
    ports:
    - containerPort: 6379
      protocol: TCP
    volumeMounts:
    - name: redis-pv
      mountPath: /shared
  volumes:
  - name: redis-pv
    persistentVolumeClaim:
      claimName: redis-pvc
