apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 6379
      protocol: TCP
    volumeMounts:
    - name: redis-nfs-pv
      mountPath: "/data"
  volumes:
  - name: redis-nfs-pv
    persistentVolumeClaim:
      claimName: redis-nfs-pvc
