apiVersion: v1
kind: PersistentVolume
metadata:
  name: redispv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/redis"
